name: Get Organization Repository Names
author: Austen Stone
description: Get all an organization's repository names to do matrix builds.
branding:
  icon: "list"
  color: "green"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  org:
    description: The org to get names from.
    default: ${{ github.event.organization.login }}
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
