name: Hello World Delim

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  get-org-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/get-org-repos@main
        with:
          github-token: ${{ secrets.TOKEN }}
          org: austenstone-ghec
          delimiter: "\n"
        id: get-org-repos
      - run: echo -e "${{ steps.get-org-repos.outputs.repos }}" > repos.txt