name: Hello World

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  get-repos:
    name: Get Repos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: get-repos
    outputs:
      repos: ${{ steps.get-repos.outputs.repos }}

  print:
    name: Print
    needs: [get-repos]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.get-repos.outputs.repos) }}
    steps:
      - run: echo "Hello ${{ matrix.repo }}!"